version: '3'

networks:
  app_net:

services:
  freelance-catcher:
    image: freelance-catcher:latest
    container_name: freelance-catcher
    restart: always
    networks:
      app_net:
    ports: [3000:3000]
    volumes: ['/home/ubuntu/freelance-catcher/:/app']

  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      app_net:
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./production/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./production/certbot/www:/var/www/certbot/:ro
      - ./production/certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    networks:
      app_net:
    volumes:
      - ./production/certbot/www/:/var/www/certbot/:rw
      - ./production/certbot/conf/:/etc/letsencrypt/:rw
