name: Freelance Catcher Deploy
on: [push]
jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Install dependencies
        run: yarn

      - name: Build project
        run: yarn build

      - name: Copy files and folders to remote server
        uses: picodebr/copy-action@v1
        with:
          ssh_key: ${{ secrets.SSH_KEY }}
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_host: ${{ secrets.SSH_HOST }}
          source: .next public Dockerfile package.json next.config.js
          destination: ~/freelance-catcher

      - run: echo "🍏 This job's status is ${{ job.status }}."
